# Generated by Django 5.1.5 on 2025-01-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
