# Generated by Django 5.1.5 on 2025-01-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
